---

- name: check if reboot is required
  stat: path=/var/run/reboot-required
  register: f
  changed_when: >
    f.stat.exists or
    (reboot_uptime_days is defined and ansible_uptime_seconds / 86400 > reboot_uptime_days)
  notify: reboot node
